name: Build

on:
  push:
    branches: [ sidekick ]
  pull_request:
    branches: [ sidekick ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm test
    - name: Build standalone
      run: npm run build-standalone-prod
    - name: Upload standalone artifact
      uses: actions/upload-artifact@v2
      with:
        name: standalone
        path: dist/sidekick-packager-standalone-v**
